### ISSUE TITLE
Password for the new user configuration when connecting

### ISSUE THREAD

**Issue by karabelnikov** [bnhf/pivpn-tap-web-ui#8] opened 2022-12-07 17:30 UTC
There is no field in the web interface for specifying a password when creating a new user configuration. You can implement a field in which there will be a check, if the field is empty, then the user password for the new user configuration is not created. If you specify a password, the profile will be created using this password. And when connecting, the user will need to enter a password for his configuration. This improves the security of using profiles in a productive environment and helps prevent profile theft or unauthorized connection. Here is a screenshot of what it might look like.

![Снимок экрана 2022-12-07 221923](https://user-images.githubusercontent.com/11692792/206249412-1cae5d8a-3866-4690-8db1-b62eb144ed9c.png)

**Comment by bnhf** [comment] 2022-12-07 21:16
@karabelnikov 

This is a good idea, and I'll have a think on how I want to implement it. No timeline at the moment, but I'll let you know.

**Comment by karabelnikov** [comment] 2022-12-07 21:26
Okay, friend. Thank you. I'll be waiting. I am very interested in this project. I will continue to explore it and offer ideas or edits.

**Comment by bnhf** [comment] 2022-12-07 23:12
@karabelnikov 

Maybe you could help with a little research. It appears EasyRSA has been enhanced to support some sort of command line password passing in the form: ```./easyrsa --passout=file:passfile --passin=file:capassfile build-client-full $cn``` But I haven't found any documentation on how to use it. There's also mention of environment variables -- but again no detail.

Referenced here:
https://www.appsloveworld.com/bash/100/15/using-easy-rsa-how-to-automate-client-server-creation-process

Let me know if you come across anything that explains how these options work, hopefully with some examples.

**Comment by karabelnikov** [comment] 2022-12-08 10:55
Scott, here is a discussion of this functionality in the automatic installation script that I use. Perhaps you can get some useful information from here: https://github.com/angristan/openvpn-install/issues/389
There also seems to be a solution here, but as I understand it, it has not been tested: https://github.com/angristan/openvpn-install/pull/1015/commits/c7d8455631572d9eaab2bffedce4eeae07995554

As I understand it, the script should look like this. There is a form in which there are 2 fields, 1 name field, 2 passphrase field. The loop checks both fields during the request and, based on their data, passes the easyrsa command to generate a certificate with or without a password. If with a password. Then you need the form to transmit the data of the passphrase field, through a temporary file or something else. This is not an easy task, but it is very interesting and necessary in our project.

**Comment by bnhf** [comment] 2022-12-08 16:14
@karabelnikov 

> There also seems to be a solution here, but as I understand it, it has not been tested: [angristan/openvpn-install@c7d8455](https://github.com/angristan/openvpn-install/commit/c7d8455631572d9eaab2bffedce4eeae07995554)

I'd seen the discussion you referenced, but not the PR, so good work on referencing that!

The following appears to function from the command line, assuming a password environment variable set to PASSPHRASE and client name set to CN:

```easyrsa --passin=pass:$PASSPHRASE --passout=pass:$PASSPHRASE build-client-full $CN```

Looks like something we can work with. :-)

**Comment by bnhf** [comment] 2022-12-08 18:01
@karabelnikov 

I edited your comment immediately above, as you had a few stray spaces in the commands -- just in case somebody comes across this thread and tries to use them.

**Comment by bnhf** [comment] 2022-12-08 19:59
@karabelnikov 

OK, I've implemented this feature, and have done some basic testing. Would you mind giving it a more complete run-through? As before, I've built a fresh multi-arch container with the "beta" tag. This also includes the changes to the way the DNS fields work in Configuration - OpenVPN config. If you could test clients with and without passphrase encryption, that would be great!

**Comment by karabelnikov** [comment] 2022-12-09 11:37
**Scott, I've tested it and I can tell you about the results:**

**Problem 1**. If you try to create a user with an empty name, then for some reason the Passphrase field is also checked, although this should not be, because this field is optional for input. But it is also highlighted in red as an error.

**Problem 2**. If you create a user by specifying a name and an empty passphrase, then a user profile is created, but adding it to the OpenVPN Connect program when connecting, it asks for a password for some reason. But I clearly did not specify the password, it remained empty. However, he still demands it. Apparently, the "nopass" parameter is passed incorrectly when creating a profile.

**Problem 3**. If you create a user by specifying a name and a passphrase, then a user profile is created, but when you connect in the OpenVPN Connect program and enter a passphrase, writes an error and the connection does not occur. I attach a screenshot. Apparently he doesn't like the passphrase. But I'm sure I'm entering a passphrase, right. I set a simple passphrase: 12345678. However, the  error does not goes out and the connection does not occur.

**Problem 4**. When entering a passphrase into a string when creating a user profile, the password is displayed explicitly. This does not meet the security requirements. It is necessary that when entering a password, the characters "dots" are displayed instead of a passphrase, for example: • • • • • •

What are your ideas?

**Comment by karabelnikov** [comment] 2022-12-09 11:43
Scott, most likely we misinterpreted the line:
`easy rsa --passin=pass:$PASSPHRASE --passout=pass:$PASSPHRASE build-client-full $CN`

I found the following information:
The password to the key is transmitted via the -passion option. Openssl supports several password transfer schemes:

`--passin pass:Password` - the password Password is set directly on the command line
`--pass in env:PWD_VAR` - the password is set in the environment variable PSWD_VARCHAR
`--passing file:/path/to/key/pwd.txt` - the password is set in the file /path/to/key/pwd.txt
`--passin stdin` - read password from /dev/stdin
`--pass in fd:6` - read password from file descriptor 6

**Example**:
sudo \
  openssl ca -batch -config /etc/openvpn/keys/safessl-easyrsa.cnf \
    -out /tmp/keys/client.crt -in /tmp/keys/client_unpass.crt \
    -keyfile /etc/openvpn/keys/private/ca.key **-passin pass:Password** \
    -cert /etc/openvpn/keys/ca.crt

**Here is the detailed information**
https://www.openssl.org/docs/man1.1.1/man1/openssl.html#Pass-Phrase-Options

**Comment by karabelnikov** [comment] 2022-12-09 11:45
I assume our option:
`easyrsa --passin=pass:$PASSPHRASE build-client-full $CN`

**Comment by karabelnikov** [comment] 2022-12-09 12:13
As I understand it:
The --passion parameter is used to decrypt or remove the passphrase from the example private key.key
The --pass out parameter is used to set a passphrase on the example private key.key
They are not used at the same time. We didn't get it right, so it doesn't work right for us :)
I understand that in our case it is necessary:
`easyrsa --pass out=pass:$PASSPHRASE build-client-full $CN`

**Comment by karabelnikov** [comment] 2022-12-09 12:32
The **--passout** parameter is used to set a passphrase on the key. In our case, it is exactly what you need to use. The **--passin** parameters is used to remove the passphrase from the key.

**Comment by bnhf** [comment] 2022-12-09 14:34
@karabelnikov 

> The **--passout** parameter is used to set a passphrase on the key. In our case, it is exactly what you need to use. The **--passin** parameters is used to remove the passphrase from the key.

Nice job on the research! I've just confirmed the above, including connecting remotely using the generated .ovpn file. Where did you end up finding this correct syntax?

**Comment by karabelnikov** [comment] 2022-12-09 15:17
Scott, I've been on the Internet for a long time looking for the information we need. There is no detailed documentation on this issue, I agree. Somewhere in the discussions on the forums, after analyzing the discussions there, I came to this conclusion. Examples of creating a key with a passphrase and decrypting it were also given. I realized that we went a bit the wrong way, these parameters are used in different ways and cannot be used together.

This is a very exciting adventure :)

**Comment by bnhf** [comment] 2022-12-09 19:53
@karabelnikov 

A very exciting adventure indeed!

I did more extensive testing this time, to be sure the generated encrypted and non-encrypted configurations were working properly. So far so good, though as before I look forward to feedback from you. Of the problems you listed, I believe I have addressed 1 thru 3.

Number 4 though, is functioning as I intended. My thinking is that rather than enforcing password field parameters, that this is treated more as an encryption key. If the field was masked, it would be very easy to mistype the passphrase -- so then we're immediately talking about adding password unmasking or a second password field for verification.

It could be done of course, but my preference would be to leave it as is. Simple, but effective, when combined with the need to have the .ovpn or .zip file on hand, and the ability to revoke any suspect certificate packages.

The new multi-arch beta just finished building and uploading, so feel free to pull and kick it around a bit. Thanks again.

**Comment by bnhf** [comment] 2022-12-09 20:03
@karabelnikov 

> I understand that in our case it is necessary:
> `easyrsa --passout=pass:$PASSPHRASE build-client-full $CN`

Also, a final note on the above, despite some of what I saw online about needing to use environment variables -- it's not necessary. The passphrase can be placed directly in the above command along with the client name.

**Comment by karabelnikov** [comment] 2022-12-10 13:40
Scott, I have tested everything and I can say with confidence that the point of the problem from 1 to 3 is solved and everything works as it should! Great job!

However, I have a suggestion for improvement. I think you'll like it too.
Firstly, the form can be simplified and the fields can be made in the form of a table with columns of equal size.
Secondly, add a hint in the field `placeholder="Enter name for new certificate"` and `placeholder="Enter password for new private key"` for greater clarity.

Thirdly, as I suggested earlier, in order to secure data entry (as it is implemented with the "Password" fields), make the input secret with characters (this is achieved by specifying `<input type="password">` and setting the eye icon so that you can change `<input type="text">`. It will look very nice and correct, if necessary, the user can click on the eye icon and check the password entry and click again to hide it.

I think it's a great idea to complete the strokes with this functionality!
**Screenshots are attached!**

![Снимок экрана 2022-12-10 181931](https://user-images.githubusercontent.com/11692792/206858032-f6a34ee6-b082-43b0-ba47-a4fcd3b31817.png)

![Снимок экрана 2022-12-10 181957](https://user-images.githubusercontent.com/11692792/206858035-7a2946e0-b77b-4176-bb0a-d4076dfe7adf.png)

![view](https://user-images.githubusercontent.com/11692792/206858123-2ca8767f-014a-44a5-85e5-a1887019d2aa.svg)

![no-view](https://user-images.githubusercontent.com/11692792/206858126-e1762eb9-5fb5-49cc-846a-6c624175b6c3.svg)

**Comment by bnhf** [comment] 2022-12-10 15:12
@karabelnikov 

Thanks for testing. I'm going to go ahead and merge what's been done so far into the main branch and build a new "latest" container. I like your suggestions for putting the name and passphrase fields side-by-side and adding masking with a reveal button. Would you be willing to submit this as a PR to the newly merged code base?

**Comment by karabelnikov** [comment] 2022-12-10 19:35
@bnhf 
I did it! I will offer all edits via PR.

![Снимок экрана 2022-12-11 003329](https://user-images.githubusercontent.com/11692792/206872361-46bddfa3-2971-4e71-9c71-0924c5d6964c.png)
![Снимок экрана 2022-12-11 003355](https://user-images.githubusercontent.com/11692792/206872362-6bbadee4-1044-4241-b055-144cb7d84cef.png)
![Снимок экрана 2022-12-11 003415](https://user-images.githubusercontent.com/11692792/206872364-a596e0e3-7157-42e5-80ff-237ab2f106d3.png)

**Comment by bnhf** [comment] 2022-12-10 22:57
@karabelnikov 

Shura, the new beta is available with your PR merged, and it mostly looks good. However, there is an issue with the Create New Certificate box. Name and Passphrase are right next to each other in my browser (Chrome):

![Screenshot 2022-12-10 154722](https://user-images.githubusercontent.com/41088895/206878338-456e2455-5111-4f8c-a5c3-cf7d5e7731e9.png)

Also, there's no unmask icon showing up in the Passphrase field. You can ignore the little white and green Roboform icon, that's just offering to fill the password.

**Comment by karabelnikov** [comment] 2022-12-10 23:05
@bnhf 

Scott, you just need to clear the cache and cookies in the browser history. Most likely, the updated custom.css is not being pulled up and therefore styles have not been applied.

**Comment by bnhf** [comment] 2022-12-10 23:16
@karabelnikov 

Right you are, I just needed to clear "Cached images and files" in Chrome. Thanks! Looks great.

**Comment by bnhf** [comment] 2022-12-11 16:40
@karabelnikov 

There's a new container with the "beta" tag available that incorporates your PRs from today. Looks good -- thanks.

**Closed** 2022-12-12 00:47 UTC
Labels: enhancement, beta available
